language: java

env:
 global:
  - EnableNuGetPackageRestore=true 

addons:
 postgresql: "9.3"

before_install:
 - wget http://download.opensuse.org/repositories/home:/tpokorra:/mono/xUbuntu_12.04/amd64/mono-opt_3.6.0_amd64.deb
 - sudo dpkg -i mono-opt_3.6.0_amd64.deb
 - export PATH=/opt/mono/bin:$PATH
 - sudo mozroots --import --sync
 - wget http://www.csie.ntu.edu.tw/~cjlin/cgi-bin/liblinear.cgi?+http://www.csie.ntu.edu.tw/~cjlin/liblinear+zip -O liblinear-1.94.zip
 - unzip liblinear-1.94.zip
 - cd liblinear-1.94 && make && cd ..

before_script:
 - psql -U postgres -c "CREATE DATABASE test"
 - psql -U postgres -d test -c "CREATE EXTENSION postgis"

script:
 - chmod +x .nunit.sh
 - ./.nunit.sh AttTest/bin/Release/AttTest.dll