language: java

env:
 global:
  - EnableNuGetPackageRestore=true 

addons:
 postgresql: "9.3"

before_install:

 # install mono
 - wget http://ptl.sys.virginia.edu/msg8u/mono-opt_3.6.0_amd64.deb
 - sudo dpkg -i mono-opt_3.6.0_amd64.deb
 - export LD_LIBRARY_PATH=/opt/mono/lib
 - export PATH=/opt/mono/bin:$PATH
 - sudo apt-get install libgdiplus
 - sudo ln -s /usr/lib/libgdiplus.so /opt/mono/lib/libgdiplus.so
 - mozroots --import --sync

 # install r
 - sudo apt-get install r-base

 # install liblinear
 - wget http://www.csie.ntu.edu.tw/~cjlin/cgi-bin/liblinear.cgi?+http://www.csie.ntu.edu.tw/~cjlin/liblinear+zip -O liblinear-1.94.zip
 - unzip liblinear-1.94.zip
 - cd liblinear-1.94 && make && cd ..

install:
 - cp AttTest/Config/* GUI/Config/
 - xbuild /p:Configuration=Release

before_script:
 - psql -U postgres -c "CREATE DATABASE test"
 - psql -U postgres -d test -c "CREATE EXTENSION postgis"
 - chmod +x .nunit.sh

script:
 - ./.nunit.sh AttTest/bin/Release/AttTest.dll